---
# tasks file for deploy

  - name: Install acl
    ansible.builtin.package:
      name: acl
      state: present

  - name: Install docker python package
    pip:
      name: docker-compose

  - name: Ensure deploy user is present and has SSH keys
    user:
      name: deploy
      home: /home/deploy
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Pull changes from Git
    ansible.builtin.git:
      accept_hostkey: yes
      repo: "{{ repository_url }}"
      dest: "{{ project_directory }}"
      update: yes
      force: yes
      version: "{{ git_branch }}"

  - name: include NGINX tasks
    include_tasks: nginx.yml
    when: nginx_config == "true"

  - name: Build & start docker-compose
    become_user: deploy
    community.docker.docker_compose:
      project_src: "{{ project_directory }}"
      build: yes
      files: "{{ compose_file }}"
      env_file: "{{ project_directory }}/{{ env_file }}"
      nocache: true
      state: present
      restarted: yes
    when: testing == "false"
