- name: Copy NGINX custom configuration file for reverse-proxy into place.
  template:
    src: templates/reverse-proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse-proxy.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - validate nginx configuration
    - reload nginx
  ignore_errors: yes


- name: Create a symbolic link to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    owner: root
    group: root
    state: link
  notify:
    - validate nginx configuration
    - reload nginx