- name: Remove default NGINX site config
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default


- name: Copy NGINX custom configuration file for reverse-proxy into place.
  template:
    src: templates/reverse-proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse-proxy.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - validate nginx configuration
    - reload nginx

- name: Create a symbolic link to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    owner: root
    group: root
    state: link
  notify:
    - validate nginx configuration
    - reload nginx